; =============================================================
; WindMonitorESP32 — PlatformIO Build Configuration
; ESP32-WROOM-32D / DevKit V4
; =============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    mathieucarbou/ESPAsyncWebServer @ ^3.1.5
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0
    robtillaart/INA226 @ ^0.6.0
