#!/usr/bin/env python3
"""
generate_web_assets.py — Embeds data/ web files as gzipped C byte arrays into src/network/web_assets.h
"""
import os
import gzip

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT_DIR, "data")
OUTPUT_HEADER = os.path.join(ROOT_DIR, "src", "network", "web_assets.h")

FILES = [
    ("INDEX_HTML_GZ", "index.html"),
    ("STYLE_CSS_GZ",  "style.css"),
    ("SCRIPT_JS_GZ",  "script.js"),
    ("FAVICON_ICO_GZ","favicon.ico")
]

def generate_header():
    lines = [
        "#pragma once",
        "// =============================================================",
        "//  web_assets.h — Pre-compressed GZIP Web Dashboard Assets",
        "//  Auto-generated by tools/generate_web_assets.py",
        "//  Stored in PROGMEM (Flash) for fail-safe zero-dependency serving",
        "// =============================================================",
        "",
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        ""
    ]

    total_raw = 0
    total_gz = 0

    for var_name, filename in FILES:
        path = os.path.join(DATA_DIR, filename)
        if not os.path.exists(path):
            continue
        with open(path, "rb") as f:
            raw_data = f.read()
        gz_data = gzip.compress(raw_data, compresslevel=9)

        total_raw += len(raw_data)
        total_gz += len(gz_data)

        lines.append(f"// {filename} (Raw: {len(raw_data)} bytes -> GZ: {len(gz_data)} bytes)")
        lines.append(f"const size_t {var_name}_LEN = {len(gz_data)};")
        lines.append(f"const uint8_t {var_name}[] PROGMEM = {{")

        # Format hex values in rows of 16
        hex_rows = []
        for i in range(0, len(gz_data), 16):
            chunk = gz_data[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            hex_rows.append(f"    {hex_str}")

        lines.append(",\n".join(hex_rows))
        lines.append("};")
        lines.append("")

    lines.append(f"// Total: Raw {total_raw} bytes -> GZIP {total_gz} bytes ({total_gz/1024:.2f} KB in Flash)")
    lines.append("")

    with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[Assets] Generated {OUTPUT_HEADER}")
    print(f"[Assets] Total Raw: {total_raw} bytes -> GZ: {total_gz} bytes ({total_gz/1024:.2f} KB)")

if __name__ == "__main__":
    generate_header()
